spring:
  application:
    name: namf-authorization
  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  messages:
    basename: messages

jwt:
  key:
    value: ${SECRET_KEY}
  expiration:
    access: 3600000
    refresh: 7

